//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBudgetApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbModel : DbContext
    {
        public DbModel()
            : base("name=DbModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Expences> Expences { get; set; }
        public virtual DbSet<ExpenceTypes> ExpenceTypes { get; set; }
        public virtual DbSet<Incomes> Incomes { get; set; }
        public virtual DbSet<IncomeTypes> IncomeTypes { get; set; }
        public virtual DbSet<Months> Months { get; set; }
    }
}
